# ===========================================
# Application
# ===========================================
spring.application.name=Threat-Intelligence-System
server.port=8080


server.address=0.0.0.0


# ===========================================
# Oracle Database
# ===========================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=Oracle123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===========================================
# Hibernate / JPA
# ===========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===========================================
# Thymeleaf
# ===========================================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# ===========================================
# File Upload
# ===========================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===========================================
# Gmail SMTP
# ===========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Replace with your Gmail
spring.mail.username=avishal@gmail.com

# Replace with Gmail App Password
spring.mail.password=Admin@123

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# ===========================================
# Logging
# ===========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===========================================
# Date & Time
# ===========================================
spring.jackson.time-zone=Asia/Kolkata
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss

# ===========================================
# Error Handling
# ===========================================
server.error.include-message=always
server.error.include-binding-errors=always

# ===========================================
# Encoding
# ===========================================
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true


# ===========================================
# Gmail SMTP
# ===========================================